### ISSUE TITLE
[Task][Setting] stack 세팅 및 용도 협의

### ISSUE THREAD

**Issue by gongdlida** [codestates/Knock-Knock-Client#17]
## Work Description
- before setting workplace, have a meeting with InSoo about what the stack's for.
- after doing that, we'll adjust npm, node.js version and set the tools  

## TODO:
1. [x] Job1 : talking about tools
2. [x] Job2 : adjusting versions.
3. [x] Job3 : setting env
