### ISSUE TITLE
[Task][todo] todo List

### ISSUE THREAD

**Issue by gongdlida** [codestates/Knock-Knock-Client#38]
## 메인페이지
 - [x] application intro 만들기 [ing]

### 모달
 - [x] 로그인 전 후 기능변경

#### 히스토리
 - [x]  회고삭제
 - [x]  참여게시물삭제
 - [x] 참여게시물 클릭했을 때 회고 작성란 출력
 - [x] 회고 작성 후 서버에 보내기  
 - [x]  마이페이지가기 버튼
 - [x]  email.js

#### 계정관리
 - [x] 개인정보 저장 시 서버에 요청
 - [x] 저장버튼 누르면 마이페이지로 이동
 - [x] 스택 일단 체크박스
 - [x] 스택 선택 후 서버에 보내기
 - [x]  프로필 스택 로고 출력하기

#### 게시판
 - [x] 필터버튼 눌렀을 때 필터되는 것
 - [x] 방만들기 눌렀을 때 createRoom 이동

### 방만들기
 - [x] 방만들기 눌렀을 때 게시판에 방생성
 - [x]  완료번트 누르면 서버에 요청 / 게시판으로 가기
     
### 방정보
 - [x] 백/프론트 체크박스 만들기
 - [x] 참여하기 버튼 누르면 서버에 보내기
      - [x] 카테고리별  참여/포지션 구분하기 
 - [x] 댓글삭제
 - [x] 방정보 출력[피그마대로]  [ui]

마무리가 되는대로  S3에 넣고 back_end 분들께 전달하기
[데드라인은 23일]
