### ISSUE TITLE
[Task][Plan] Css todo list

### ISSUE THREAD

**Issue by gongdlida** [codestates/Knock-Knock-Client#43]
## 메인페이지
- [x] 메인페이지는 밑에 있는 기능들이 모두 끝나면 모든 시간을 쏟아서 한다.

#### 상단 네비게이션 바
 - [x] 이미지 수정 (전체적인 색깔 수정)

#### 모달
 - [x] 비율조정
 - [x]  왼쪽상단의 knock-knock 로고 [home 링크 삭제하고 로고 대체]
 - [x]  오른쪽 상단 로그인 / 비로그인 시 버튼 외부 디자인
 - [x]  로그인/비로그인 시 모달 클릭했을 때 내부 디자인

## 마이페이지
 - [x] 비율조정

#### 마이페이지
 - [x] 프로필 사진 추가하기
 - [x] 프로필 로고 이미지 출력되게 하기
 - [x] 열린게시물 / 닫힌게시물에서 마우스 터치 전 나오는 정보 수정 [타이틀/상태 open or closed]
 - [x] 열린게시물 / 닫힌게시물 마우스 터치 시 정보에 따라 Flex box 크기 증가.
 - [x] 현재 방정보에 대한 글에 "<>"가 나오는 것 제거

#### 히스토리
 - [x] 레포삭제 버튼 디자인
 - [x] 회고 받아오기 버튼 디자인
 - [x] overflow: scroll로 인한 스크롤 라인 제거
 - [x] 회고 삭제버튼 디자인 [게시판 댓글 삭제하는 것과 동일한 디자인]
 - [x] 레포부분 폭 맞추기 [프로젝트종류/프로젝트명/스택/스택종류]
 - [x] 스택 세부사항은 레포 클릭시 오른쪽 회고창에서 타이틀 밑에 글씨를 연하게 사용해서 보여주기

#### 계정관리
 - [x] 비율조정
 - [x] 계정관리 우측 계정 수정하는 곳에 flex box 넣기 [피그마 참고]
 - [x] 스택 선택부분 이미지 클릭해서 만들기
 - [x] 계정관리 username 미등록 시 활동제한 / 경고 주기
 - [x] 오른쪽 정보를 입력하는 곳에 박스 만들기

## 게시판 [오늘 끝내보자] 
 - [x]  비율조정
 - [x] 사이드바 보더라인 없애기
 - [x] 카드 사진 비율 조정 및 보정
 - [x]  카드 디자인 바꾸기 [슬랙으로 보낸 디자인참고]

#### 방만들기
 - [x] 로고 선택하는 부분 이미지로 클릭해서 선택 [O-auth 디자인과 비슷하게]
 - [x] question일 때에는 설문지 없애기
 - [x] 방생성 항목 미 작성시 경고창 띄우기
  
#### 방정보
 - [x] 폰트를 반응형으로 설정하기 [현재 모바일 화면에서 비율이 깨짐] 
 - [x] 참가 신청 및 방 생성자에게 포지션 선택 및 신청하기 버튼 없애기
 - [x] 카테고리마다 고유 정보 출력 [스택/포지션/이미지]
 - [x] 로그인/비로그인 시 신청하기 버튼 출력 설정하기 => 버튼 클릭시 로그인 유도로 변경
 - [x] 로그인/비로그인 시 textarea 출력 설정하기 => 버튼 클릭시 로그인 유도로 변경

## 수정해야할 컴포넌트
- [x] 로그아웃 세션지우기 
- [x] Category에 따른 ui 출력값 다르게 하기

비율조정은 css 세부사항이 끝나면 함께 조정.
[데드라인은 30일]
