### ISSUE TITLE
[Task][Plan] 중복되는 요소 모듈화

### ISSUE THREAD

**Issue by gongdlida** [codestates/Knock-Knock-Client#7]
## Work Description
- 와이어프램임을 보고 중복되는 요소 확인
## TODO: 
1. [x] Job1 : 피그마 이미지를 보고 중복되는 요소를 찾는다.

- [x] 1-1: Nav bar [로고/시작하기/문]
- [x] 1-2: MyPage [sideBar]

2. [x] job2: 중복되는 요소는 페이지 라우팅 후 바로 만들어 적용시켜본다.
